drop table if exists clients CASCADE;
drop table if exists users CASCADE;
drop table if exists accounts CASCADE;
drop table if exists cards CASCADE;


create table clients (
                                id int generated by default as identity,
                                name varchar(255) not null,
                                primary key (id)
);

create table accounts (
                               id int generated by default as identity,
                               number varchar(20) not null UNIQUE,
                               balance decimal,
                               client_id int,
                               primary key (id),
                               foreign key (client_id) references clients(id)
);


create table cards (
                          id int generated by default as identity,
                          number varchar(16) not null unique,
                          account_id int,
                          is_active boolean default (false),
                          primary key (id),
                          foreign key (account_id) references accounts(id)
);

