drop table if exists clients CASCADE;
drop table if exists users CASCADE;
drop table if exists accounts CASCADE;
drop table if exists cards CASCADE;
drop table if exists payments CASCADE;
drop table if exists counterparties CASCADE;


create table clients
(
    id   int generated by default as identity,
    name varchar(255) not null,
    primary key (id)
);

create table accounts
(
    id        int generated by default as identity,
    number    varchar(20) not null UNIQUE,
    balance   decimal,
    client_id int,
    primary key (id),
    foreign key (client_id) references clients (id)
);


create table cards
(
    id         int generated by default as identity,
    number     varchar(16) not null unique,
    account_id int,
    is_active  boolean default (false),
    primary key (id),
    foreign key (account_id) references accounts (id)
);

create table counterparties
(
    id              int generated by default as identity,
    party_id        int,
    counterparty_id int,
    primary key (id),
    foreign key (party_id) references clients (id),
    foreign key (counterparty_id) references clients (id),
    UNIQUE (party_id, counterparty_id)
);

create table payments
(
    id       int generated by default as identity,
    amount   decimal,
    approved boolean default (false),
    from_id  int,
    to_id    int,
    primary key (id),
    foreign key (from_id) references accounts (id),
    foreign key (to_id) references accounts (id)
);

